### PR TITLE
fix: Stop RM errors when using acceleratedDHT

### LINKED ISSUE #9405: 0.17.0-rc1: ResourceMgr defaults clash with  AcceleratedDHTClient
### Version

```Text
0.17.0-rc1
```

### Config

```json
> ipfs config --json Swarm.ConnMgr # these are defaults from 0.17.0-rc1
{
  "GracePeriod": "20s",
  "HighWater": 900,
  "LowWater": 600,
  "Type": "basic"
}

$ ipfs config --json Experimental.AcceleratedDHTClient
true
```

### Description

Enabling `Experimental.AcceleratedDHTClient`  with `ResourceMgr` does not work with defaults from 0.17.0-rc1, user gets vague ERROR message which  is then overrun by resourcemanager errors:

```
2022-11-14T17:17:03.911Z	ERROR	fullrtdht	fullrt/dht.go:309	Accelerated DHT client was unable to fully refresh its routing table due to Resource Manager limits, which may degrade content routing. Consider increasing resource limits. See debug logs for the "dht-crawler" subsystem for details.
2022-11-14T17:17:13.135Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:53	Resource limits were exceeded 168 times with error "transient: cannot reserve connection: resource limit exceeded".
2022-11-14T17:17:13.135Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:53	Resource limits were exceeded 177 times with error "transient: cannot reserve outbound connection: resource limit exceeded".
2022-11-14T17:17:13.135Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:57	Consider inspecting logs and raising the resource manager limits. Documentation: https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmresourcemgr
2022-11-14T17:17:23.135Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:53	Resource limits were exceeded 42 times with error "system: cannot reserve connection: resource limit exceeded".
2022-11-14T17:17:23.135Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:57	Consider inspecting logs and raising the resource manager limits. Documentation: https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmresourcemgr
2022-11-14T17:17:33.136Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:53	Resource limits were exceeded 80627 times with error "system: cannot reserve connection: resource limit exceeded".
2022-11-14T17:17:33.136Z	ERROR	resourcemanager	libp2p/rcmgr_logging.go:57	Consider inspecting logs and raising the resource manager limits. Documentation: https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmresourcemgr
```

Given that we suggest enabling this setting to everyone running a Server, it feels we should do more here, either in docs or general UX.

## Potential fix?

- proper fix: make accelerated DHT client adjust its work based on limits  + if limit is lower than X, print one-time WARNING recommending increasing the connection limits for best performance.
- short term, or if proper fix is not feasible:  we could update https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#accelerated-dht-client with example how to raise relevant limits, and link to it from the error message:
  ```
  2022-11-14T17:17:03.911Z	ERROR	fullrtdht	fullrt/dht.go:309	Accelerated DHT client was unable    to fully refresh its routing table due to ResourceMgr limits, which may degrade content routing. Consider increasing resource limits. See debug logs for the "dht-crawler" subsystem for details, and 
  ```

### PR DESCRIPTION
**Pull request by ajnavarro**
- Move Transient limits back to only limit inbound connections and streams.
- Remove the usage of HighWater param.

It closes #9405 

Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

### CODE REVIEW

File: core/node/groups.go [hunk 1]
```diff
@@ -147,7 +147,7 @@ func LibP2P(bcfg *BuildCfg, cfg *config.Config) fx.Option {
 		BaseLibP2P,
 
 		// Services (resource management)
-		fx.Provide(libp2p.ResourceManager(cfg.Swarm)),
+		fx.Provide(libp2p.ResourceManager(cfg.Swarm, cfg.Experimental.AcceleratedDHTClient)),
```
Comment (BigLep) [inline core/node/groups.go:150]:
```suggestion
		fx.Provide(libp2p.ResourceManager(cfg.Swarm)),
```

File: core/node/libp2p/rcmgr.go [hunk 2]
```diff
@@ -29,7 +29,7 @@ const NetLimitTraceFilename = "rcmgr.json.gz"
 
 var ErrNoResourceMgr = fmt.Errorf("missing ResourceMgr: make sure the daemon is running with Swarm.ResourceMgr.Enabled")
 
-func ResourceManager(cfg config.SwarmConfig) interface{} {
+func ResourceManager(cfg config.SwarmConfig, acceleratedDHT bool) interface{} {
```
Comment (BigLep) [inline core/node/libp2p/rcmgr.go:32]:
```suggestion
func ResourceManager(cfg config.SwarmConfig) interface{} {
```

**Review by BigLep — COMMENTED** [review]
@ajnavarro : thinking on this more, I think we should just remove the connection with between the resource manager and "cfg.ConnMgr.HighWater".  Lets let them operate independently.  I made a commit with my suggested code change.

Can you then confirm that this works with both the scenarios that @lidel mentioned in https://github.com/ipfs/kubo/issues/9405 and https://github.com/ipfs/kubo/issues/9406 ?

Thanks

**Comment by ajnavarro** [comment]
@BigLep confirmed that it works with both ConnMgr configurations.

File: core/node/libp2p/rcmgr_defaults.go [hunk 3]
```diff
@@ -132,9 +140,29 @@ func createDefaultLimitConfig(cfg config.SwarmConfig) (rcmgr.LimitConfig, error)
...
-		TransientLimitIncrease: rcmgr.DefaultLimits.TransientLimitIncrease,
+		TransientBaseLimit: rcmgr.BaseLimit{
+			Streams:         bigEnough,
+			StreamsInbound:  rcmgr.DefaultLimits.TransientBaseLimit.StreamsInbound,
+			StreamsOutbound: bigEnough,
+			Conns:           bigEnough,
+			ConnsInbound:    rcmgr.DefaultLimits.TransientBaseLimit.ConnsInbound,
+			ConnsOutbound:   bigEnough,
+			FD:              rcmgr.DefaultLimits.TransientBaseLimit.FD,
+			Memory:          rcmgr.DefaultLimits.TransientBaseLimit.Memory,
```
Comment (BigLep) [inline core/node/libp2p/rcmgr_defaults.go:151]:
```suggestion
			Memory:          rcmgr.DefaultLimits.TransientBaseLimit.Memory,
			FD:              rcmgr.DefaultLimits.TransientBaseLimit.FD,
			
			Conns:           bigEnough,
			ConnsInbound:    rcmgr.DefaultLimits.TransientBaseLimit.ConnsInbound,
			ConnsOutbound:   bigEnough,
			
			Streams:         bigEnough,
			StreamsInbound:  rcmgr.DefaultLimits.TransientBaseLimit.StreamsInbound,
			StreamsOutbound: bigEnough,
```

nit: putting in the same ordering as used throughout the code.

**Review by BigLep — APPROVED** [review]
Looks good to me given it's passing the configurations that @lidel mentioned.

We'll need to cut a new RC for this.
