### PR TITLE
fix(gw): 404 when a valid DAG is missing link

### LINKED ISSUE #8924: Investigate why /ipfs/{invalid cid} returns different Status Code now
`curl -v http://127.0.0.1:8080/ipfs/2329.png` returned:
-  returned `400 Bad Request` in 0.12.2
- now returns  `404 Not Found` (master @ 25cc85fa9359f907f348e0c2139f2b535313c56c)

IIUC this a low impact change, and we should be ok with 404 (comment below if you think otherwise), but would be useful to understand how it happened.

Potential causes:
-  ErrNotFound changes from https://github.com/ipfs/go-ipfs/pull/8838
- refactors like https://github.com/ipfs/go-ipfs/pull/8855
- ?

### LINKED ISSUE #9064: Gateway incorrectly reports NotFound when any error encountered reading UnixFS
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
Commit 862ce6bb8f6ce24b91ed3dc59e7406faed34f583 (27 June 2022)
```

### Config

_No response_

### Description

When serving a UnixFS file the gateway will return a NotFound error whenever any error was encounted reading the UnixFS dag. 

See https://github.com/ipfs/go-ipfs/blob/862ce6bb8f6ce24b91ed3dc59e7406faed34f583/core/corehttp/gateway_handler_unixfs.go#L25

The gateway should distinguish between missing nodes, transient network errors and invalid paths and give appropriate HTTP responses for each

It's possible that https://github.com/ipfs/go-ipfs/issues/8924 may be related

### PR DESCRIPTION
**Pull request by lidel**
This PR makes sure gateway returns 404 (Not Found) only when a valid DAG is missing the requested child.
In other cases, 400 (Bad Request) is returned.

Uses `ipld.IsNotFound` added in https://github.com/ipfs/kubo/pull/8838

Closes #8924 
Closes #9064

### CODE REVIEW

File: core/corehttp/gateway_handler.go [hunk 1]
```diff
@@ -782,6 +782,8 @@ func webError(w http.ResponseWriter, message string, err error, defaultCode int)
 		webErrorWithCode(w, message, err, http.StatusNotFound)
 	} else if err == routing.ErrNotFound {
 		webErrorWithCode(w, message, err, http.StatusNotFound)
+	} else if ipld.IsNotFound(err) {
+		webErrorWithCode(w, message, err, http.StatusNotFound)
```
Comment (lidel) [inline core/corehttp/gateway_handler.go:786]: :information_source: this makes sure every `webError` gets 404 when appropriate

File: core/corehttp/gateway_test.go [hunk 2]
```diff
@@ -235,17 +235,17 @@ func TestGatewayGet(t *testing.T) {
 		{"127.0.0.1:8080", "/", http.StatusNotFound, "404 page not found\n"},
 		{"127.0.0.1:8080", "/" + k.Cid().String(), http.StatusNotFound, "404 page not found\n"},
 		{"127.0.0.1:8080", k.String(), http.StatusOK, "fnord"},
-		{"127.0.0.1:8080", "/ipns/nxdomain.example.com", http.StatusNotFound, "ipfs resolve -r /ipns/nxdomain.example.com: " + namesys.ErrResolveFailed.Error() + "\n"},
-		{"127.0.0.1:8080", "/ipns/%0D%0A%0D%0Ahello", http.StatusNotFound, "ipfs resolve -r /ipns/\\r\\n\\r\\nhello: " + namesys.ErrResolveFailed.Error() + "\n"},
+		{"127.0.0.1:8080", "/ipns/nxdomain.example.com", http.StatusBadRequest, "ipfs resolve -r /ipns/nxdomain.example.com: " + namesys.ErrResolveFailed.Error() + "\n"},
```
Comment (iand) [inline core/corehttp/gateway_test.go:238]: Note I think resolution errors should be reported as 502 Bad Gateway but that's not what the gateway spec says. I'll raise an issue there instead

**Review by iand — COMMENTED** [review]
LGTM

File: core/corehttp/gateway_test.go (hunk 2 above)
Comment (lidel) [reply core/corehttp/gateway_test.go:238]: @iand how so? In my mind, it is a bad request  (requesting path that has no DNSLink).
