### PR TITLE
fix(core/commands/pin): return error if listing an invalid, but known, pin type

### LINKED ISSUE #11237: ipfs pin ls --type=internal reports "Error: an error occurred"
### Checklist

- [x] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [x] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

dist.ipfs.tech or ipfs-update

### Version

```Text
Kubo version: 0.40.1-39f8a6554
Repo version: 18
System version: amd64/linux
Golang version: go1.25.7
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/webrtc-direct",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/webrtc-direct",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoConf": {},
  "AutoNAT": {},
  "AutoTLS": {},
  "Bitswap": {},
  "Bootstrap": [
    "auto"
  ],
  "DNS": {
    "Resolvers": {
      ".": "auto"
    }
  },
  "Datastore": {
    "BlockKeyCacheSize": null,
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "mountpoint": "/blocks",
          "path": "blocks",
          "prefix": "flatfs.datastore",
          "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
          "sync": false,
          "type": "flatfs"
        },
        {
          "compression": "none",
          "mountpoint": "/",
          "path": "datastore",
          "prefix": "leveldb.datastore",
          "type": "levelds"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "Libp2pStreamMounting": false,
    "OptimisticProvide": false,
    "OptimisticProvideJobsPoolSize": 0,
    "P2pHttpProxy": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "AllowCodecConversion": null,
    "DeserializedResponses": null,
    "DisableHTMLErrors": null,
    "ExposeRoutingAPI": null,
    "HTTPHeaders": {},
    "NoDNSLink": false,
    "NoFetch": false,
    "PublicGateways": null,
    "RootRedirect": ""
  },
  "HTTPRetrieval": {},
  "Identity": {
    "PeerID": "12D3KooWJ9gmDVxdhkoWvRwMz1nuK4RSDcitTBAootayC4ZjBBn2"
  },
  "Import": {
    "BatchMaxNodes": null,
    "BatchMaxSize": null,
    "CidVersion": null,
    "FastProvideRoot": null,
    "FastProvideWait": null,
    "HashFunction": null,
    "UnixFSChunker": null,
    "UnixFSDAGLayout": null,
    "UnixFSDirectoryMaxLinks": null,
    "UnixFSFileMaxLinks": null,
    "UnixFSHAMTDirectoryMaxFanout": null,
    "UnixFSHAMTDirectorySizeEstimation": null,
    "UnixFSHAMTDirectorySizeThreshold": null,
    "UnixFSRawLeaves": null
  },
  "Internal": {},
  "Ipns": {
    "DelegatedPublishers": [
      "auto"
    ],
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {},
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns",
    "MFS": "/mfs"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provide": {
    "DHT": {}
  },
  "Provider": {},
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {},
  "Routing": {
    "DelegatedRouters": [
      "auto"
    ]
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  },
  "Version": {}
}
```

### Description

This is what is displayed in a terminal where I ran "ipfs daemon":
2026-03-16T23:53:28.203+0100    ERROR   cmds/http       http/handler.go:96      a panic has occurred in the commands handler!
2026-03-16T23:53:28.203+0100    ERROR   cmds/http       http/handler.go:97      unhandled pin type
2026-03-16T23:53:28.203+0100    ERROR   cmds/http       http/handler.go:98      stack trace:
goroutine 2948 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP.func1()
        github.com/ipfs/go-ipfs-cmds@v0.16.0/http/handler.go:98 +0xef
panic({0x30f61c0?, 0x3ce2230?})
        runtime/panic.go:783 +0x132
github.com/ipfs/kubo/core/commands/pin.pinLsAll(0xc002443500, {0xc0018467bc, 0x8}, 0x0, {0x0, 0x0}, {0x3d31780, 0xc000efcc00}, 0xc001bdaa18)
        github.com/ipfs/kubo@v0.40.1/core/commands/pin/pin.go:573 +0x688
github.com/ipfs/kubo/core/commands/pin.init.func3(0xc002443500, {0x78328e104490, 0xc00125d300}, {0x347f220, 0xc001eb74f0})
        github.com/ipfs/kubo@v0.40.1/core/commands/pin/pin.go:423 +0x4b9
github.com/ipfs/go-ipfs-cmds.(*Command).call(0xc001bdac70?, 0xc002443500, {0x78328e104490, 0xc00125d300}, {0x347f220, 0xc001eb74f0})
        github.com/ipfs/go-ipfs-cmds@v0.16.0/command.go:189 +0x189
github.com/ipfs/go-ipfs-cmds.(*Command).Call(0x51fcaa0?, 0x352e0c0?, {0x78328e104490, 0xc00125d300}, {0x347f220?, 0xc001eb74f0?})
        github.com/ipfs/go-ipfs-cmds@v0.16.0/command.go:159 +0x3f
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP(0xc001e6fe80, {0x3d0a120, 0xc0018c7b60}, 0xc00210c500)
        github.com/ipfs/go-ipfs-cmds@v0.16.0/http/handler.go:202 +0xa79
github.com/ipfs/go-ipfs-cmds/http.prefixHandler.ServeHTTP({{0x3692ba4?, 0x12a4d14?}, {0x3cf2d00?, 0xc001e6fe80?}}, {0x3d0a120, 0xc0018c7b60}, 0xc00210c500)
        github.com/ipfs/go-ipfs-cmds@v0.16.0/http/apiprefix.go:24 +0x142
github.com/ipfs/go-ipfs-cmds/http.NewHandler.(*Cors).Handler.func1({0x3d0a120, 0xc0018c7b60}, 0xc00210c500)
        github.com/rs/cors@v1.11.1/cors.go:289 +0x164
net/http.HandlerFunc.ServeHTTP(0x3d0fdb0?, {0x3d0a120?, 0xc0018c7b60?}, 0x3cd8c48?)
        net/http/server.go:2322 +0x29
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0xc001f1e180, {0x78328e104360, 0xc001b9cfa0}, 0xc00210c3c0, {0x3cf0b40, 0xc001e6fec0})
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.65.0/handler.go:178 +0x12c3
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x78328e104360?, 0xc001b9cfa0?}, 0xc001bdb478?)
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.65.0/handler.go:66 +0x35
net/http.HandlerFunc.ServeHTTP(0xc001f1e000?, {0x78328e104360?, 0xc001b9cfa0?}, 0x13d123d?)
        net/http/server.go:2322 +0x29
net/http.(*ServeMux).ServeHTTP(0xc000059650?, {0x78328e104360, 0xc001b9cfa0}, 0xc00210c3c0)
        net/http/server.go:2861 +0x1c7
github.com/ipfs/kubo/cmd/ipfs/kubo.serveHTTPApi.CheckVersionOption.func8.1({0x78328e104360, 0xc001b9cfa0}, 0xc00210c3c0)
        github.com/ipfs/kubo@v0.40.1/core/corehttp/commands.go:230 +0x245
net/http.HandlerFunc.ServeHTTP(0xc000d7fb00?, {0x78328e104360?, 0xc001b9cfa0?}, 0x35dd500?)
        net/http/server.go:2322 +0x29
net/http.(*ServeMux).ServeHTTP(0x52038e0?, {0x78328e104360, 0xc001b9cfa0}, 0xc00210c3c0)
        net/http/server.go:2861 +0x1c7
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x78328e104360?, 0xc001b9ceb0?}, 0xc00210c3c0)
        github.com/prometheus/client_golang@v1.23.2/prometheus/promhttp/instrument_server.go:296 +0xcf
net/http.HandlerFunc.ServeHTTP(0x1?, {0x78328e104360?, 0xc001b9ceb0?}, 0xc002ac37b0?)
        net/http/server.go:2322 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2({0x78328e104360?, 0xc001b9ceb0?}, 0xc00210c3c0)
        github.com/prometheus/client_golang@v1.23.2/prometheus/promhttp/instrument_server.go:255 +0x7d
net/http.HandlerFunc.ServeHTTP(0x78328d790600?, {0x78328e104360?, 0xc001b9ceb0?}, 0xc000619008?)
        net/http/server.go:2322 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x78328e104360, 0xc001b9ceb0}, 0xc00210c3c0)
        github.com/prometheus/client_golang@v1.23.2/prometheus/promhttp/instrument_server.go:109 +0xc5
net/http.HandlerFunc.ServeHTTP(0x5203860?, {0x78328e104360?, 0xc001b9ceb0?}, 0xe?)
        net/http/server.go:2322 +0x29
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x3d06c90?, 0xc001f2c780?}, 0xc00210c3c0)
        github.com/prometheus/client_golang@v1.23.2/prometheus/promhttp/instrument_server.go:147 +0xc3
net/http.HandlerFunc.ServeHTTP(0xc000d7fa40?, {0x3d06c90?, 0xc001f2c780?}, 0xc000c88a70?)
        net/http/server.go:2322 +0x29
net/http.(*ServeMux).ServeHTTP(0xc002ac3b10?, {0x3d06c90, 0xc001f2c780}, 0xc00210c3c0)
        net/http/server.go:2861 +0x1c7
github.com/ipfs/kubo/core/corehttp.MakeHandler.func1({0x3d06c90?, 0xc001f2c780?}, 0x134e433?)
        github.com/ipfs/kubo@v0.40.1/core/corehttp/corehttp.go:52 +0x65
net/http.HandlerFunc.ServeHTTP(0x13099b9?, {0x3d06c90?, 0xc001f2c780?}, 0xc002ac3b68?)
        net/http/server.go:2322 +0x29
net/http.serverHandler.ServeHTTP({0xc0026e6cc0?}, {0x3d06c90?, 0xc001f2c780?}, 0x1?)
        net/http/server.go:3340 +0x8e
net/http.(*conn).serve(0xc000996b40, {0x3d0fdb0, 0xc001f27470})
        net/http/server.go:2109 +0x665
created by net/http.(*Server).Serve in goroutine 1852
        net/http/server.go:3493 +0x485

### PR DESCRIPTION
**Pull request by aschmahmann**
fixes #11237

### CODE REVIEW

File: core/commands/pin/pin.go [hunk 1]
```diff
@@ -570,7 +570,7 @@ func pinLsAll(req *cmds.Request, typeStr string, detailed bool, name string, api
 
 	opt, err := options.Pin.Ls.Type(typeStr)
 	if err != nil {
-		panic("unhandled pin type")
```
Comment (aschmahmann) [inline core/commands/pin/pin.go:573]: Do we even need this first check on `pin.StringToMode`?

Comment (gammazero) [reply core/commands/pin/pin.go:573]: assuming they support the same values, then no

Comment (lidel) [reply core/commands/pin/pin.go:573]: there are two sets, one is CLI, one is boxo internals.

`options.Pin.Ls.Type()` is actually the stricter check,  it only accepts `{direct, indirect, recursive, all}`, while `StringToMode` also accepts `internal`, `not pinned`, and `any`. So `Pin.Ls.Type` catches everything `StringToMode` would, plus more.

we have good tests, but were missing one for the delta between these, so added a test to this PR for `internal`, probably good enough for now
