### PR TITLE
fix(config): wire up `Provider.Enabled` flag

### LINKED ISSUE #10803: kubo 0.35.0-rc1: missing Provide.Enabled flag
### Checklist

- [x] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [x] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

dist.ipfs.tech or ipfs-update

### Version

```Text
0.35.0-rc1
```

### Config

```json
default
```

### Description

Kubo has ability to disable DHT announcements by setting `Reprovider.Interval` to `0`.

(Un)fortunately 0.35.0-rc1 (https://github.com/ipfs/kubo/issues/10760) included https://github.com/ipfs/boxo/pull/907 which introduced separate queue for initial provides, which does not seem to be covered by this setting, which makes it impossible to disable DHT announcements of newly added data.

## Proposed fix

- Introduce explicit `Provider.Enabled` (type `Flag`, true by default) for controlling initial provides
  - ❓  ~~OR should it be `Provider.Strategy` as `OptionalString` and two options `all|off` with `all` being default (allowing us to have more in future?)~~
  - Keep it a bool for clarity.
- To keep things simple, disable both systems if either `Reprovider.Interval=0` or `Provider.Enabled=false` + log a message informing user that provides are disabled as well, to remove any surprises.
  - We can do deeper refactor later, to allow disabling each one separately.

### PR DESCRIPTION
**Pull request by lidel**
Kubo 0.35.0-rc1 had issues on Staging environment due too OOMs ([internal notes](https://www.notion.so/Kubo-0-34-1-vs-0-35-0-1ed1def342878037b7c1f8b67d7c986b?pvs=4#1ed1def342878070ba3ec1e526d86761)).

@guillaumemichel and @gammazero  suggested that the problem is related to provides, which should be disabled on that box.  This PR aims to implement ability to fully disable provides (and reprovides) as noted in #10803 and unblock Kubo 0.35 (https://github.com/ipfs/kubo/issues/10760)

### TODO

- [x] Add [`Provider.Enabled`](https://github.com/ipfs/kubo/blob/master/docs/config.md#providerenabled) is a global flag for disabling both [Provider](https://github.com/ipfs/kubo/blob/master/docs/config.md#provider) and [Reprovider](https://github.com/ipfs/kubo/blob/master/docs/config.md#reprovider) systems (announcing new/old CIDs to amino DHT).
- [x] Remove `Experimental.StrategicProviding`. Superseded by `Provider.Enabled`, `Reprovider.Interval` and [`Reprovider.Strategy`](https://github.com/ipfs/kubo/blob/master/docs/config.md#reproviderstrategy).
  - [x] update tests
- [x] Lower default for `Provider.WorkerCount` when no Accelerated DHT client
- [x] Add/Update CLI tests of `routing [re]provide` commands, ensure global flags are respected
- [x] CI green
- [x] Deploy to staging and see if OOM is still present: https://github.com/ipshipyard/waterworks-infra/pull/604
  - [x] [OOMd right after it started](https://grafana.ipshipyard.dev/d/c3b61616-3e32-47e2-850b-04d48e0daaf0/ipfs-rainbow-gateway?orgId=1&from=2025-05-13T21:30:00.000Z&to=2025-05-13T22:17:34.651Z&timezone=utc&var-instance=kubo-staging-us-east-01&var-instance=kubo-staging-us-east-02&refresh=1m&viewPanel=panel-5), but then looked stable. I'm going to let it [run for a longer time](https://grafana.ipshipyard.dev/d/c3b61616-3e32-47e2-850b-04d48e0daaf0/ipfs-rainbow-gateway?orgId=1&from=2025-05-13T21:30:00.000Z&to=now&timezone=utc&var-instance=kubo-staging-us-east-01&var-instance=kubo-staging-us-east-02&refresh=1m&viewPanel=panel-5) to see if it occurs as often as in 0.34.1 
- [x] (optional) make extra test where we re-enable [re]provider and see behavior with lowered `Provider.WorkerCount` 
  - [x] done ([internal notes](https://www.notion.so/Kubo-0-34-1-vs-0-35-0-1ed1def342878037b7c1f8b67d7c986b?pvs=4#1f41def34287804db785f093aa9385d4)) – updated docs in https://github.com/ipfs/kubo/pull/10804/commits/e8ec3fde17c14a192866dbc9637c18c27e0c734c 
- [x] Merge if staging OOMs are gone

### CODE REVIEW

File: cmd/ipfs/kubo/daemon.go [hunk 1]
```diff
@@ -625,17 +630,19 @@ take effect.
...
 ⚠️ Local CIDs will not be announced to Amino DHT, making them impossible to retrieve without manual peering
-⚠️ If this is not intentional, call 'ipfs config profile apply announce-on'
+⚠️ If this is not intentional, call 'ipfs config profile apply announce-on' or set Provide.Enabled=true'
 
 `)
 		} else if cfg.Reprovider.Interval.WithDefault(config.DefaultReproviderInterval) == 0 {
 			fmt.Print(`
-⚠️ Reprovider system is disabled due to 'Reprovider.Interval=0'
+
+⚠️ Provide and Reprovide systems are disabled due to 'Reprovider.Interval=0'
```
Comment (guillaumemichel) [inline cmd/ipfs/kubo/daemon.go:645]: Provide System isn't disabled in this case, only reprovides are disabled.

File: core/commands/routing.go [hunk 2]
```diff
@@ -254,6 +263,18 @@ Trigger reprovider to announce our data to network.
...
+		cfg, err := nd.Repo.Config()
+		if err != nil {
+			return err
+		}
+		if !cfg.Provider.Enabled.WithDefault(config.DefaultProviderEnabled) {
+			return errors.New("invalid configuration: Provider.Enabled is set to 'false'")
+		}
+		if cfg.Reprovider.Interval.WithDefault(config.DefaultReproviderInterval) == 0 {
+			return errors.New("invalid configuration: Reprovider.Interval is set to '0'")
+		}
```
Comment (guillaumemichel) [inline core/commands/routing.go:276]: Currently, setting `Reprovider.Interval` to `0` disables periodic reprovides, however manual reprovides (triggered by the `reprovide` command) are still possible. Do we want to disable this feature?

File: core/node/groups.go [hunk 3]
```diff
@@ -337,16 +337,26 @@ func Online(bcfg *BuildCfg, cfg *config.Config, userResourceOverrides rcmgr.Part
 
 	isBitswapLibp2pEnabled := cfg.Bitswap.Libp2pEnabled.WithDefault(config.DefaultBitswapLibp2pEnabled)
 	isBitswapServerEnabled := cfg.Bitswap.ServerEnabled.WithDefault(config.DefaultBitswapServerEnabled)
+	isHTTPRetrievalEnabled := cfg.HTTPRetrieval.Enabled.WithDefault(config.DefaultHTTPRetrievalEnabled)
 
-	// Don't provide from bitswap when the legacy noop experiment "strategic provider service" is active
-	isBitswapServerEnabled = isBitswapServerEnabled && !cfg.Experimental.StrategicProviding
+	// Right now Provider and Reprovider systems are tied together - disabling Reprovider by setting interval to 0 disables Provider
+	// and vice versa: Provider.Enabled=false will disable both Provider of new CIDs and the Reprovider of old ones.
+	isProviderEnabled := cfg.Provider.Enabled.WithDefault(config.DefaultProviderEnabled) && cfg.Reprovider.Interval.WithDefault(config.DefaultReproviderInterval) != 0
```
Comment (guillaumemichel) [inline core/node/groups.go:344]: When `Reprovide.Interval` is set to `0` do we want to 1) only disable periodic reprovides, while leaving initial provide and manual reprovides enabled or 2) disable DHT providing altogether?

File: docs/config.md [hunk 4]
```diff
@@ -1706,6 +1724,10 @@ not being able to discover that you have the objects that you have. If you want
 to have this disabled and keep the network aware of what you have, you must
 manually announce your content periodically.
 
+> [!CAUTION]
+> Setting `Reprovider.Interval=0` will only disable the periodic reprovides.
+> New CIDs will stil lbe announced. To disable both, set [`Provider.Enabled=false`](#providerenabled) as well.
```
Comment (guillaumemichel) [inline docs/config.md:1729]:
```suggestion
> New CIDs will still be announced. To disable both, set [`Provider.Enabled=false`](#providerenabled) as well.
```

**Review by guillaumemichel — APPROVED** [review]
Just wondering whether we actually want `Reprovide.Interval=0` to disable the provide system altogether? (see comments)

File: cmd/ipfs/kubo/daemon.go (hunk 1 above)
Comment (lidel) [reply cmd/ipfs/kubo/daemon.go:645]: No, I changed approach because there were too many adge cases – disabling either of systems disables both.

File: core/node/groups.go (hunk 3 above)
Comment (lidel) [reply core/node/groups.go:344]: I believe we want to disable provider here because many users set `Reprovide.Interval`  set to `0` to stop providing. 

If we don't disable it, then many users will suddenly become providers for 48h.

Imo manual provides are not something many people use without also having regular provide and reprovide system enabled – what I've seen is people running everything + often abused DHT by doing extra manual provides in a tight loop.

Note: times changed. We now have useful `Reprovider.Strategy` which allow users to fine-tune what is reprovided without having to disable entire system. We should discourage disabling entire system, and encourage fine-tuning what is reprovided.

File: docs/config.md (hunk 4 above)
Comment (lidel) [reply docs/config.md:1729]: Good catch, I'll update this section, it is outdated.

**Comment by lidel** [comment]
Confirmed this PR (mainly, ability to disable provider queue) restores goroutine/memory utilization that is on par or better than v0.34.1 ([internal notes](https://www.notion.so/Kubo-0-34-1-vs-0-35-0-1ed1def342878037b7c1f8b67d7c986b?pvs=4#1ed1def34287804da66ee1b15aed68e6) from our staging env).

Merging – will include this in 0.35.0-rc2.
