### PR TITLE
fix(daemon): webui URL when RPC listener is 0.0.0.0

### LINKED ISSUE #10515: Could not connect to the IPFS API from WebUI at http://0.0.0.0:5001/webui
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

_No response_

### Config

_No response_

### Description

using the original docker-compose.yml to start. it shows 

CleanShot 2024-09-15 at 17 41 17@2x

do we need some other init process for this compose?

### PR DESCRIPTION
**Pull request by lidel**
Closes #10515

### Before

```console
$ ipfs daemon
Initializing daemon...
...
RPC API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
```

### After 

```console
$ ipfs daemon
Initializing daemon...
...
RPC API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://127.0.0.1:5001/webui
```

### CODE REVIEW

File: cmd/ipfs/kubo/daemon.go [hunk 1]
```diff
@@ -706,10 +706,18 @@ func serveHTTPApi(req *cmds.Request, cctx *oldcmds.Context) (<-chan error, error
...
+		// Browsers require TCP with explicit host.
 		switch listener.Addr().Network() {
 		case "tcp", "tcp4", "tcp6":
-			fmt.Printf("WebUI: http://%s/webui\n", listener.Addr())
+			rpc := listener.Addr().String()
+			// replace catch-all with explicit localhost URL that works in browsers
+			// https://github.com/ipfs/kubo/issues/10515
+			if strings.Contains(rpc, "0.0.0.0:") {
+				rpc = strings.Replace(rpc, "0.0.0.0:", "127.0.0.1:", 1)
+			} else if strings.Contains(rpc, "[::]:") {
```
Comment (gammazero) [inline cmd/ipfs/kubo/daemon.go:717]: Should this be done in a separate `case "tcp6":`?

**Review by gammazero — APPROVED** [review]

File: cmd/ipfs/kubo/daemon.go (hunk 1 above)
Comment (lidel) [reply cmd/ipfs/kubo/daemon.go:717]: probably not worth refactoring, this only executes once on daemon start
