### PR TITLE
fix: Provide according to Reprovider.Strategy

### LINKED ISSUE #10837: Provide newly received blocks according to reprovide strategy
### Checklist

- [x] My issue is specific & actionable.
- [x] I am not suggesting a protocol enhancement.
- [x] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

## Context

It seems that kubo/boxo is providing all newly received blocks to the DHT ([source](https://github.com/ipfs/boxo/blob/364c5040ec91ec8e2a61446e9921e9225704c34d/exchange/providing/providing.go#L41)).

These blocks will not be reprovided if they don't match the [reprovider strategy](https://github.com/ipfs/kubo/blob/master/docs/config.md#reproviderstrategy).

What was the rationale for this?

## Proposed solutions

a) It seems reasonable to apply the reprovider strategy on newly received blocks as well. This would reduce the number of provides, and allow the (re)provider system to manage the reprovides by itself, independently from the blockstore.

b) If providing all newly received blocks is actually desirable, I suggest changing the provider interface to let the (re)provider system to provide the key once only (and not reprovide it).

## Motivation

A change is required to allow the DHT [`SweepingReprovider`](https://github.com/libp2p/go-libp2p-kad-dht/pull/1082) to track which keys must be reprovided.

* https://github.com/ipfs/kubo/issues/10097
* https://github.com/libp2p/go-libp2p-kad-dht/pull/1082
* https://github.com/ipfs/kubo/pull/10834

### PR DESCRIPTION
**Pull request by hsanjuan**
This updates boxo to this PR https://github.com/ipfs/boxo/pull/976, which decentralizes the providing responsibilities.

Then it perfoms the necessary changes in Kubo, which consist in initializing the Pinner, MFS and the blockstore with the provider.System.

Since the provider.System is created first, the reproviding KeyChanFunc is set later when we can create it.

Aims to Close #10837

### CODE REVIEW

**Comment by hsanjuan** [comment]
Pre weekend note: we will need to provide blocks as we add them, when strategy is "pinned". The blockstore won't do it and the pinner won't do it since it doesn't fetch the DAG in that case (we just pin the root directly).

Right now seems the cleanest would be to have a ProvideMany-DAGService that we can use core for coreunix/add. It should take advantage of batched AddMany with ProvideMany.

Second note: `ipfs add --offline` will provide when the daemon is running and strategy=all since the blockstore will provide the blocks on write and has no way of knowing if the user called things with `--offline`. We should consider not overwriting the provider at all in the coreapi as `--offline` is not going to work consistently when the daemon is running in online fashion.

Third note: these new behaviors affect tests that need to be updated. Particularly we now provide immediately where we didn't before. For example on `ipfs add` did not provide immediately anymore since it did not hit the providing.Exchange, and now it will do.

File: core/coreapi/coreapi.go [hunk 1]
```diff
@@ -44,6 +45,8 @@ import (
 	"github.com/ipfs/kubo/repo"
 )
 
+var log = logging.Logger("coreapi")
```
Comment (hsanjuan) [inline core/coreapi/coreapi.go:48]: New logging facility, did not exist before. Anything else to do?

File: core/coreapi/coreapi.go [hunk 2]
```diff
@@ -70,7 +73,8 @@ type CoreAPI struct {
 	ipldPathResolver   pathresolver.Resolver
 	unixFSPathResolver pathresolver.Resolver
 
-	provider provider.System
+	provider          provider.System
+	providingStrategy string
```
Comment (hsanjuan) [inline core/coreapi/coreapi.go]: Carry the strategy so we can react on it when adding content.

File: core/coreapi/pin.go [hunk 3]
```diff
@@ -44,10 +44,6 @@ func (api *PinAPI) Add(ctx context.Context, p path.Path, opts ...caopts.PinAddOp
 		return fmt.Errorf("pin: %s", err)
 	}
 
-	if err := api.provider.Provide(ctx, dagNode.Cid(), true); err != nil {
-		return err
-	}
-
```
Comment (hsanjuan) [inline core/coreapi/pin.go:50]: Previously, at the end of the Pin process, coreapi would trigger a Provide for the root CID (regardless of prividing strategy).

We now provide according to strategy, and this does not need to happen here (happens in the pinner).

File: core/coreapi/unixfs.go [hunk 4]
```diff
@@ -102,7 +103,21 @@ func (api *UnixfsAPI) Add(ctx context.Context, files files.Node, opts ...options
...
+	//   - "all"/"flat" gets handled directly at the blockstore so no need to provide
+	//   - "roots" gets handled in the pinner
+	//   - "mfs" gets handled in mfs
+	// We need to provide the "pinned" cases only. Added blocks are not
+	// going to be provided by the blockstore (wrong strategy for that),
+	// nor by the pinner (it does not traverse the pinned DAG).
+	if settings.Pin && !settings.OnlyHash &&
+		(api.providingStrategy == "pinned" || api.providingStrategy == "pinned+mfs") {
+		dserv = &providingDagService{dserv, api.provider}
+	}
```
Comment (hsanjuan) [inline core/coreapi/unixfs.go]: Per the comment, we need to ensure we provide blocks while Adding with the "pinned" strategy as this cannot happen in the Pinner (it doesn't traverse the DAG itself). For that, we wrap the DagService.

File: core/coreapi/unixfs.go [hunk 5]
```diff
@@ -183,7 +200,7 @@ func (api *UnixfsAPI) Add(ctx context.Context, files files.Node, opts ...options
 		if err != nil {
 			return path.ImmutablePath{}, err
 		}
-		mr, err := mfs.NewRoot(ctx, md, emptyDirNode, nil)
+		mr, err := mfs.NewRoot(ctx, md, emptyDirNode, nil, nil)
```
Comment (hsanjuan) [inline core/coreapi/unixfs.go:208]: new `nil` is the provider, which we leave disabled for MFS here. We are using a providing DAG service when needed.

Could we potentially passed a provider around and initialize MFS with it here and have it provide this way, rather than wrapping the DAGService? Potentially yes, but I'm not sure what happens with file-chunks and if MFS touches them at all. If not, I would need to wire the chunkers too etc. Overall it seemed more complex and fragile to do it that way.

File: core/coreapi/unixfs.go [hunk 6]
```diff
@@ -196,12 +213,6 @@ func (api *UnixfsAPI) Add(ctx context.Context, files files.Node, opts ...options
 		return path.ImmutablePath{}, err
 	}
 
-	if !settings.OnlyHash {
-		if err := api.provider.Provide(ctx, nd.Cid(), true); err != nil {
-			return path.ImmutablePath{}, err
-		}
-	}
-
```
Comment (hsanjuan) [inline core/coreapi/unixfs.go:204]: Did this not happen from the providing.Exchange already? This might have been a leftover from long ago. Traceable to https://github.com/ipfs/kubo/commit/a9b65346871e845a67bbd19c668b699c55095e41.

Anyways, no need to do this here as we will respect the strategy.

File: core/coreapi/unixfs.go [hunk 7]
```diff
@@ -367,3 +378,33 @@ type syncDagService struct {
...
+
+func (pds *providingDagService) AddMany(ctx context.Context, nds []ipld.Node) error {
+	if err := pds.DAGService.AddMany(ctx, nds); err != nil {
+		return err
+	}
+	for _, n := range nds {
+		if err := pds.provider.Provide(ctx, n.Cid(), true); err != nil {
+			log.Error(err)
+			break
+		}
```
Comment (hsanjuan) [inline core/coreapi/unixfs.go:417]: The fact that this a reprovider means it will internally use ProvideMany on the real provider when possible. ProvideMany() is not available to us here directly. Plus with upcoming changes it has no point to bring it up here.

File: core/coreunix/add.go [hunk 8]
```diff
@@ -416,15 +416,15 @@ func (adder *Adder) addFileNode(ctx context.Context, path string, file files.Nod
...
+		return adder.addSymlink(ctx, path, f)
 	case files.File:
 		return adder.addFile(path, f)
 	default:
 		return errors.New("unknown file type")
 	}
 }
 
-func (adder *Adder) addSymlink(path string, l *files.Symlink) error {
+func (adder *Adder) addSymlink(ctx context.Context, path string, l *files.Symlink) error {
```
Comment (hsanjuan) [inline core/coreunix/add.go:427]: added for no reason, but doesn't hurt.

File: core/node/core.go [hunk 9]
```diff
@@ -47,25 +48,38 @@ func BlockService(cfg *config.Config) func(lc fx.Lifecycle, bs blockstore.Blocks
 }
 
 // Pinning creates new pinner which tells GC which blocks should be kept
-func Pinning(bstore blockstore.Blockstore, ds format.DAGService, repo repo.Repo) (pin.Pinner, error) {
-	rootDS := repo.Datastore()
+func Pinning(reprovidingStrategy string) func(bstore blockstore.Blockstore, ds format.DAGService, repo repo.Repo, prov provider.System) (pin.Pinner, error) {
```
Comment (hsanjuan) [inline core/node/core.go]: We cannot use the fx-provided reprovidingStrategy here, as that is only set when the reprovider is created, and the reprovider needs the pinner.

File: core/node/core.go [hunk 10]
```diff
@@ -202,7 +216,7 @@ func Files(mctx helpers.MetricsCtx, lc fx.Lifecycle, repo repo.Repo, dag format.
 		return nil, err
 	}
 
-	root, err := mfs.NewRoot(ctx, dag, nd, pf)
+	root, err := mfs.NewRoot(ctx, dag, nd, pf, prov)
```
Comment (hsanjuan) [inline core/node/core.go]: FIXME: provider should be nil'ed when not "mfs" or "mfs+pinned" ?

File: core/node/provider.go [hunk 11]
```diff
@@ -26,12 +28,11 @@ const sampledBatchSize = 1000
...
 const reprovideStrategyKey = "/reprovideStrategy"
 
-func ProviderSys(reprovideInterval time.Duration, acceleratedDHTClient bool, provideWorkerCount int, reprovideStrategy string) fx.Option {
-	return fx.Provide(func(lc fx.Lifecycle, cr irouting.ProvideManyRouter, keyProvider provider.KeyChanFunc, repo repo.Repo, bs blockstore.Blockstore) (provider.System, error) {
+func ProviderSys(reprovideInterval time.Duration, acceleratedDHTClient bool, provideWorkerCount int) fx.Option {
+	return fx.Provide(func(lc fx.Lifecycle, cr irouting.ProvideManyRouter, repo repo.Repo) (provider.System, error) {
 		opts := []provider.Option{
 			provider.Online(cr),
 			provider.ReproviderInterval(reprovideInterval),
-			provider.KeyProvider(keyProvider),
```
Comment (hsanjuan) [inline core/node/provider.go:34]: We will set the key provider once we have created the pinner, blockstore etc. Now the provider.System is initialized first!

File: core/node/provider.go [hunk 12]
```diff
@@ -223,30 +204,71 @@ func newProvidingStrategy(strategy string) interface{} {
...
 					mfsRootProvider(in.MFSRoot),
 				),
-				provider.NewBlockstoreProvider(in.Blockstore),
+				in.Blockstore.AllKeysChan,
 			)
 		}
+
+		in.Provider.SetKeyProvider(kcf)
+
+		var strategyChanged bool
```
Comment (hsanjuan) [inline core/node/provider.go]: The strategy-change detection has been moved here. No changes in code blocks below.

File: test/cli/harness/run.go [hunk 13]
```diff
@@ -89,6 +89,7 @@ func (r *Runner) Run(req RunRequest) *RunResult {
 	for k, v := range r.Env {
 		cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", k, v))
 	}
+	// cmd.Env = append(cmd.Env, `GOLOG_LOG_LEVEL=provider=debug,pin=debug,blockstore=debug,merkledag=debug`)
```
Comment (hsanjuan) [inline test/cli/harness/run.go]: Remove, leftover from testing.

**Review by hsanjuan — COMMENTED** [review]
Self review and clarifications

File: core/coreapi/coreapi.go (hunk 1 above)
Comment (gammazero) [reply core/coreapi/coreapi.go:48]: That all that is needed.

File: core/coreapi/unixfs.go [hunk 14]
```diff
@@ -126,6 +141,8 @@ func (api *UnixfsAPI) Add(ctx context.Context, files files.Node, opts ...options
 		}
 	}
 
+	// reminder: the dag server gets wrapped again (!) as a batching dagservice in coreunix.Adder.
```
Comment (gammazero) [inline core/coreapi/unixfs.go]: Where does this happen? Does this refer to where a batch is created in the `dag put` command?

File: core/coreapi/unixfs.go [hunk 15]
```diff
@@ -102,7 +103,21 @@ func (api *UnixfsAPI) Add(ctx context.Context, files files.Node, opts ...options
...
+	// wrap the DAGService in a providingDAG service which provides every block written.
+	// note about strategies:
+	//   - "all"/"flat" gets handled directly at the blockstore so no need to provide
+	//   - "roots" gets handled in the pinner
+	//   - "mfs" gets handled in mfs
+	// We need to provide the "pinned" cases only. Added blocks are not
+	// going to be provided by the blockstore (wrong strategy for that),
+	// nor by the pinner (it does not traverse the pinned DAG).
+	if settings.Pin && !settings.OnlyHash &&
+		(api.providingStrategy == "pinned" || api.providingStrategy == "pinned+mfs") {
```
Comment (gammazero) [inline core/coreapi/unixfs.go]: Would it be better to look for "pinned" in case there is a future strategy that is "pinned+something"?
```suggestion
		strings.Contains(api.providingStrategy, "pinned") {
```

Or should the strategy consist of bit-flags instead?

File: core/coreiface/tests/routing.go [hunk 16]
```diff
@@ -171,6 +171,12 @@ func (tp *TestSuite) TestRoutingFindProviders(t *testing.T) {
 		t.Fatal(err)
 	}
 
+	// Pin so that it is provided as providing strategy is "roots"
```
Comment (gammazero) [inline core/coreiface/tests/routing.go]:
```suggestion
	// Pin so that it is provided as if providing strategy is "roots"
```

File: core/node/core.go [hunk 17]
```diff
@@ -152,63 +166,73 @@ func Dag(bs blockservice.BlockService) format.DAGService {
...
-		}
-	case err == nil:
-		c, err := cid.Cast(val)
-		if err != nil {
+		var nd *merkledag.ProtoNode
+		ctx := helpers.LifecycleCtx(mctx, lc)
+		val, err := repo.Datastore().Get(ctx, dsk)
+
+		switch {
+		case err == datastore.ErrNotFound || val == nil:
```
Comment (gammazero) [inline core/node/core.go]: Checking `val == nil` seems wrong, because `val` should be `nil` for any non-nil error that is returned. Also, it would be better to use `errors.Is` instead of direct comparison.

```suggestion
		case errors.Is(err, datastore.ErrNotFound):
```

File: core/node/core.go [hunk 18]
```diff
@@ -152,63 +166,73 @@ func Dag(bs blockservice.BlockService) format.DAGService {
...
-		pbnd, ok := rnd.(*merkledag.ProtoNode)
-		if !ok {
-			return nil, merkledag.ErrNotProtobuf
+		// disable providing from mfs when the strategy does not
+		// need that.
+		switch reprovidingStrategy {
+		case "mfs", "pinned+mfs":
+		default:
+			prov = nil
 		}
```
Comment (gammazero) [inline core/node/core.go]:
```suggestion
		if !strings.Contains(reprovidingStrategy, "mfs") {
			prov = nil
		}
```

File: core/coreapi/unixfs.go (hunk 15 above)
Comment (gammazero) [reply core/coreapi/unixfs.go]: The strategy names should also be defined as `const`, instead of using the strings directly.

File: core/node/provider.go [hunk 19]
```diff
@@ -50,16 +51,20 @@ func ProviderSys(reprovideInterval time.Duration, acceleratedDHTClient bool, pro
 						defer cancel()
 
 						// FIXME: I want a running counter of blocks so size of blockstore can be an O(1) lookup.
-						ch, err := bs.AllKeysChan(ctx)
+						// Note: talk to datastore directly, as to not depend on Blockstore here.
+						qr, err := repo.Datastore().Query(ctx, query.Query{
+							Prefix:   "/blocks",
```
Comment (guillaumemichel) [inline core/node/provider.go]: Is this prefix defined somewhere we can reuse? We wouldn't have to hardcode `"/blocks"`?

File: docs/changelogs/v0.37.md [hunk 20]
```diff
@@ -44,6 +45,17 @@ $ ipfs pin ls --names
 bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi recursive testname
 ```
 
+#### `Reprovider.Strategy` is now consistently respected
+
+Prior to this version, files added, blocks received etc. were "provided" to the network (that means they were announced on the DHT) regardless of the ["reproviding strategy" setting](https://github.com/ipfs/kubo/blob/master/docs/config.md#reproviderstrategy). For example, if the strategy was set to "pinned", and `ipfs add --pin=false` was used, the file would be provided regarless. If the strategy was set to "roots" and `ipfs pin add` was used, all the blocks (not only the root) would be provided. Only the "reproviding" action (which runs every 22h by default) would respect the strategy.
```
Comment (guillaumemichel) [inline docs/changelogs/v0.37.md]:
```suggestion
Prior to this version, files added, blocks received etc. were "provided" to the network (that means they were announced on the DHT) regardless of the ["reproviding strategy" setting](https://github.com/ipfs/kubo/blob/master/docs/config.md#reproviderstrategy). For example, if the strategy was set to "pinned", and `ipfs add --pin=false` was used, the file would be provided regardless. If the strategy was set to "roots" and `ipfs pin add` was used, all the blocks (not only the root) would be provided. Only the "reproviding" action (which runs every 22h by default) would respect the strategy.
```

File: docs/changelogs/v0.37.md [hunk 21]
```diff
@@ -44,6 +45,17 @@ $ ipfs pin ls --names
...
+
+Needless to say, this was innefficient as content that should not be provided was getting provided once. From now on, all operations respect `Reproviding.Strategy`. If it's set to "roots", no blocks other than pin roots will be provided regardless of what is fetched, added etc.
+
+There's a small behaviour change:
+  * When running `ipfs daemon` (in online mode)
+  * And running `ipfs --offline add` (while the **online** daemon is running)
+  * Then: the blocks will be provided according to the strategy where, before, the blocks were not provided. Otherwise said, the `--offline` flag in the client-command has no effect on providing anymore as the operation is controlled by the running "online" daemon and its reproviding strategy. `ipfs --offline add` used to give a performance bonus vs running it without `--offline`, but now it is performant regardless of it. To run an offline dameon you can always do `ipfs --offline daemon`. All operations against that daemon will be offline then.
```
Comment (guillaumemichel) [inline docs/changelogs/v0.37.md]:
```suggestion
  * Then: the blocks will be provided according to the strategy where, before, the blocks were not provided. Otherwise said, the `--offline` flag in the client-command has no effect on providing anymore as the operation is controlled by the running "online" daemon and its reproviding strategy. `ipfs --offline add` used to give a performance bonus vs running it without `--offline`, but now it is performant regardless of it. To run an offline daemon you can always do `ipfs --offline daemon`. All operations against that daemon will be offline then.
```

File: docs/changelogs/v0.37.md [hunk 22]
```diff
@@ -44,6 +45,17 @@ $ ipfs pin ls --names
...
 
+#### `Reprovider.Strategy` is now consistently respected
+
+Prior to this version, files added, blocks received etc. were "provided" to the network (that means they were announced on the DHT) regardless of the ["reproviding strategy" setting](https://github.com/ipfs/kubo/blob/master/docs/config.md#reproviderstrategy). For example, if the strategy was set to "pinned", and `ipfs add --pin=false` was used, the file would be provided regarless. If the strategy was set to "roots" and `ipfs pin add` was used, all the blocks (not only the root) would be provided. Only the "reproviding" action (which runs every 22h by default) would respect the strategy.
+
+Needless to say, this was innefficient as content that should not be provided was getting provided once. From now on, all operations respect `Reproviding.Strategy`. If it's set to "roots", no blocks other than pin roots will be provided regardless of what is fetched, added etc.
+
+There's a small behaviour change:
+  * When running `ipfs daemon` (in online mode)
+  * And running `ipfs --offline add` (while the **online** daemon is running)
```
Comment (guillaumemichel) [inline docs/changelogs/v0.37.md]: Does it make sense to keep the `--offline` flag for `ipfs add`, or should we mark it as deprecated?

File: core/coreapi/unixfs.go (hunk 14 above)
Comment (hsanjuan) [reply core/coreapi/unixfs.go]: Here: https://github.com/ipfs/kubo/blob/96aa0523fbe53a845137b4418881e7ca36b2fd34/core/coreunix/add.go#L52

There is a normal DAGService, which gets wrapped in a providing DAGService, which gets wrapped in a SyncDAGService, which gets wrapped in a Buffered DAGService.

File: core/coreapi/unixfs.go (hunk 15 above)
Comment (hsanjuan) [reply core/coreapi/unixfs.go]: Yeah, this is bothering me, I will switch them to bit flags.

File: test/cli/provider_test.go [hunk 23]
```diff
@@ -131,16 +134,94 @@ func TestProvider(t *testing.T) {
...
 
 		nodes := initNodes(t, 2, func(n *harness.Node) {
 			n.SetIPFSConfig("Reprovider.Strategy", "all")
 		})
 		defer nodes.StopDaemons()
 
-		cid := nodes[0].IPFSAddStr(time.Now().String(), "--local")
+		cid := nodes[0].IPFSAddStr("all strategy")
+		expectProviders(t, cid, nodes[0].PeerID().String(), nodes[1:]...)
+	})
```
Comment (guillaumemichel) [inline test/cli/provider_test.go:188]: Maybe duplicate this test to confirm that the `""` strategy behaves like `"all"`.

File: core/node/core.go (hunk 17 above)
Comment (hsanjuan) [reply core/node/core.go]: This code is just re-indented I think, it's been like that for 6 years https://github.com/ipfs/kubo/commit/d35dac70f0b0b47c7813c6380deb8974179bdb32. 

I'll take your proposal though.

File: test/cli/provider_test.go [hunk 24]
```diff
@@ -131,16 +134,94 @@ func TestProvider(t *testing.T) {
...
+		data := testutils.RandomBytes(1000)
+		cid := nodes[0].IPFSAdd(bytes.NewReader(data), "-Q")
 
+		// not yet in MFS
+		expectNoProviders(t, cid, nodes[1:]...)
+
+		nodes[0].IPFS("files", "cp", "/ipfs/"+cid, "/myfile")
+		expectProviders(t, cid, nodes[0].PeerID().String(), nodes[1:]...)
+	})
+
```
Comment (guillaumemichel) [inline test/cli/provider_test.go:274]: Maybe add one more test for strategy `"pinned+mfs"`

File: core/node/groups.go [hunk 25]
```diff
@@ -442,6 +443,8 @@ func IPFS(ctx context.Context, bcfg *BuildCfg) fx.Option {
 	uio.HAMTShardingSize = int(shardSingThresholdInt)
 	uio.DefaultShardWidth = int(shardMaxFanout)
 
+	reproviderStrategy := cfg.Reprovider.Strategy.WithDefault(config.DefaultReproviderStrategy)
```
Comment (guillaumemichel) [inline core/node/groups.go]: I suggest to rename the `reproviderStrategy` to `providerStrategy` at all relevant places.

At [core/core.go](https://github.com/ipfs/kubo/blob/96aa0523fbe53a845137b4418881e7ca36b2fd34/core/core.go#L110) and [core/coreapi/coreapi.go](https://github.com/ipfs/kubo/blob/96aa0523fbe53a845137b4418881e7ca36b2fd34/core/coreapi/coreapi.go#L77), it is already called `ProvidingStrategy` (not reprovide).

IMO it makes sense to call it the _provide_ strategy, because if the system works as expected, users shouldn't need to know that there is some reproviding going on. They should only care about the provide strategy determining which CIDs are provided.

I suggest to use the (currently deprecated) [`Provider.Strategy`](https://github.com/ipfs/kubo/blob/96aa0523fbe53a845137b4418881e7ca36b2fd34/config/provider.go#L12) config field, and to deprecate the `Reprovider.Strategy` one.

File: core/node/provider.go (hunk 19 above)
Comment (hsanjuan) [reply core/node/provider.go]: switched to ` blockstore.BlockPrefix.String(),`

File: docs/changelogs/v0.37.md (hunk 22 above)
Comment (hsanjuan) [reply docs/changelogs/v0.37.md]: it sill does things (setting an offline exchange etc). In our last triage we said we could address this in a separate PR.

File: core/node/groups.go (hunk 25 above)
Comment (hsanjuan) [reply core/node/groups.go]: I tend to agree, but that would need a migration I think. Can we handle it in a different PR?

Comment (lidel) [reply core/node/groups.go]: Ok to start using "provider" in new code, but let's keep this PR and user configuration names as-is for 0.37.

We will likely have to adjust provider configuration anyway in 0.38 so let's postpone rename of public interfaces/configs until then. Once changes from https://github.com/ipfs/kubo/pull/10883 ship (includes embedded migrations), writing config migration will be way easier.

File: core/node/provider.go [hunk 26]
```diff
@@ -215,38 +194,83 @@ func mfsRootProvider(mfsRoot *mfs.Root) provider.KeyChanFunc {
...
+	Repo                 repo.Repo
+}
+
+type provStrategyOut struct {
+	fx.Out
+	ProvidingStrategy    config.ReproviderStrategy
+	ProvidingKeyChanFunc provider.KeyChanFunc
+}
+
+func setReproviderKeyProvider(strategy string) func(in provStrategyIn) provStrategyOut {
```
Comment (lidel) [inline core/node/provider.go]: This one was bit hairy, I've split it into smaller pieces in https://github.com/ipfs/kubo/pull/10886/commits/3b481cdfa00f50bb20916c1dcd1fe7d0ef1825f4

File: core/node/provider.go [hunk 27]
```diff
@@ -215,38 +194,83 @@ func mfsRootProvider(mfsRoot *mfs.Root) provider.KeyChanFunc {
...
-					provider.NewBufferedProvider(provider.NewPinnedProvider(true, in.Pinner, in.OfflineIPLDFetcher)),
+					provider.NewBufferedProvider(dspinner.NewPinnedProvider(true, in.Pinner, in.OfflineIPLDFetcher)),
 					mfsRootProvider(in.MFSRoot),
 				),
-				provider.NewBlockstoreProvider(in.Blockstore),
+				in.Blockstore.AllKeysChan,
 			)
 		}
+
+		in.Provider.SetKeyProvider(kcf)
```
Comment (lidel) [inline core/node/provider.go]: :thought_balloon:  Fx ptsd tells me setting the key provider after system creation could lead to race conditions if the provider system starts before the key provider is set. 

Unsure how real this fear is – these things usually happen years later during refactors   so probably not worth worrying.

**Review by lidel — COMMENTED** [review]
Pushed some extra go comments with context from this and boxo PRs +  small refactor.

Lgtm, but want to run some additional manual tests before merging.
Will post once done.

**Review by lidel — APPROVED** [review]
Thank you @hsanjuan, this should make future changes easier to reason about. Lgtm, pushed extra docs/tests.

Ok to squash&merge, but would like you to take one final look at split I did in https://github.com/ipfs/kubo/pull/10886/commits/3b481cdfa00f50bb20916c1dcd1fe7d0ef1825f4 and give :+1: 

If no concerns my plan is to merge this by the end of this week (end of Friday 8th) to unblock other PRs that depend on latest boxo (e.g.  https://github.com/ipfs/kubo/pull/10851#discussion_r2258309083).

File: core/coreapi/unixfs.go (hunk 14 above)
Comment (lidel) [reply core/coreapi/unixfs.go]: added a comment which documents this: https://github.com/ipfs/kubo/pull/10886/commits/c8d1f73dcee4fc3fcaa460b520a6385718f05414#diff-f95c7ebeb06be691a9a243030e11f7d3a1c4297086e8ebfa20ac3c7936878a32R145

File: core/node/groups.go (hunk 25 above)
Comment (guillaumemichel) [reply core/node/groups.go]: Ok, we can edit priv variable names when we change the public config to ProviderStrategy instead of ReproviderStrategy

File: core/node/provider.go (hunk 27 above)
Comment (hsanjuan) [reply core/node/provider.go]: It's safe? https://github.com/ipfs/boxo/blob/main/provider/reprovider.go#L259-L265

**Comment by hsanjuan** [comment]
Split looks good

**Review by guillaumemichel — APPROVED** [review]
