### PR TITLE
plugin: fix non-deterministic loading order

### LINKED ISSUE #9909: Plugin loading doesn't respect the expected order
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
master branch
```

### Config

_No response_

### Description

I'm not entirely sure if it's a bug or a massive foot-gun, but it goes like this:
- kubo use the preload_list file that list which plugin to load, and generate the corresponding loading code at compile time (ALL GOOD)
- this code take each plugin package, and for those, each actual plugin from the declared slice (ALL GOOD)
- kubo pass each of those to PluginLoader.Load() which collect them into a map (HUUU)
- kubo call PluginLoader.Inject() to trigger the actual injection by iterating on that map (PROBLEM)

Golang's map iteration is famously non-deterministic ... which means kubo load those plugins in random order, and doesn't respect an eventual ordering constraint.

### PR DESCRIPTION
**Pull request by MichaelMure**
fix #9909

### CODE REVIEW

**Review by smoyer64 — APPROVED** [review]

File: plugin/loader/loader.go [hunk 1]
```diff
@@ -140,18 +141,22 @@ func (loader *PluginLoader) Load(pl plugin.Plugin) error {
...
 
 	name := pl.Name()
-	if ppl, ok := loader.plugins[name]; ok {
-		// plugin is already loaded
-		return fmt.Errorf(
-			"plugin: %s, is duplicated in version: %s, "+
-				"while trying to load dynamically: %s",
-			name, ppl.Version(), pl.Version())
+
+	for _, p := range loader.plugins {
```
Comment (Jorropo) [inline plugin/loader/loader.go:145]: `O(n**2)`, you could use a `map[string]struct{}` to keep of already registered plugins

Comment (MichaelMure) [reply plugin/loader/loader.go:145]: Future madman that load enough plugin for that to be an issue, you are mad. Also, please ping this issue and explain why, I'm so curious.
