### PR TITLE
fix: allow custom http provide when libp2p node is offline

### LINKED ISSUE #10967: `ipfs routing provide` fails if we're not connected to peers even though we have HTTP routers configured
### Checklist

- [x] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [x] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

dist.ipfs.tech or ipfs-update

### Version

```Text
Kubo version: 0.37.0
Repo version: 17
System version: amd64/linux
Golang version: go1.25.0
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/50019",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/6473",
    "NoAnnounce": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/webrtc-direct",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/webrtc-direct",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoConf": {},
  "AutoNAT": {},
  "AutoTLS": {
    "Enabled": true
  },
  "Bitswap": {},
  "Bootstrap": [
    "auto"
  ],
  "DNS": {
    "Resolvers": {
      ".": "auto"
    }
  },
  "Datastore": {
    "BlockKeyCacheSize": null,
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "mountpoint": "/blocks",
          "path": "blocks",
          "prefix": "flatfs.datastore",
          "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
          "sync": false,
          "type": "flatfs"
        },
        {
          "compression": "none",
          "mountpoint": "/",
          "path": "datastore",
          "prefix": "leveldb.datastore",
          "type": "levelds"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "Libp2pStreamMounting": false,
    "OptimisticProvide": false,
    "OptimisticProvideJobsPoolSize": 0,
    "P2pHttpProxy": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "DeserializedResponses": null,
    "DisableHTMLErrors": null,
    "ExposeRoutingAPI": null,
    "HTTPHeaders": {},
    "NoDNSLink": false,
    "NoFetch": false,
    "PublicGateways": null,
    "RootRedirect": ""
  },
  "HTTPRetrieval": {},
  "Identity": {
    "PeerID": "12D3KooWAbynhDD3zYQbN46RM5wB1Rsxq8cfHq9H2yN8mzmfF981"
  },
  "Import": {
    "BatchMaxNodes": null,
    "BatchMaxSize": null,
    "CidVersion": null,
    "HashFunction": null,
    "UnixFSChunker": null,
    "UnixFSDirectoryMaxLinks": null,
    "UnixFSFileMaxLinks": null,
    "UnixFSHAMTDirectoryMaxFanout": null,
    "UnixFSHAMTDirectorySizeThreshold": null,
    "UnixFSRawLeaves": null
  },
  "Internal": {},
  "Ipns": {
    "DelegatedPublishers": [
      "auto"
    ],
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {},
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns",
    "MFS": "/mfs"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {},
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {},
  "Routing": {
    "Methods": {
      "find-peers": {
        "RouterName": "HttpRouterNotSupported"
      },
      "find-providers": {
        "RouterName": "HttpRoutersParallel"
      },
      "get-ipns": {
        "RouterName": "HttpRouterNotSupported"
      },
      "provide": {
        "RouterName": "HttpRoutersParallel"
      },
      "put-ipns": {
        "RouterName": "HttpRouterNotSupported"
      }
    },
    "Routers": {
      "HttpRouter1": {
        "Parameters": {
          "Endpoint": "http://127.0.0.1:19575",
          "MaxProvideBatchSize": 100,
          "MaxProvideConcurrency": 8
        },
        "Type": "http"
      },
      "HttpRouterNotSupported": {
        "Parameters": {
          "Endpoint": "http://kubohttprouternotsupported",
          "MaxProvideBatchSize": 0,
          "MaxProvideConcurrency": 0
        },
        "Type": "http"
      },
      "HttpRoutersParallel": {
        "Parameters": {
          "Routers": [
            {
              "IgnoreErrors": true,
              "RouterName": "HttpRouter1",
              "Timeout": "10s"
            }
          ]
        },
        "Type": "parallel"
      }
    },
    "Type": "custom"
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": true,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  },
  "Version": {}
}
```

### Description

If I boot up a fresh kubo node with no active peer connections with http router config to both provide and find providers from the http routers, `ipfs routing provide` will fail because we don't have any connected peers.

Expected behavior imo would be to announce the content to HTTP routers even while having no connected peers

### PR DESCRIPTION
**Pull request by guillaumemichel**
Fixes #10967

## Current state

`ipfs routing provide <cid>` fails if kubo isn't connected to any other peer (libp2p). It doesn't even attempt to provide.

## Problem

When `custom` Routing is used, it is acceptable to provide to a custom HTTP router (instead of a DHT over libp2p). If the node is configured to provide to a HTTP router, `ipfs routing provide <cid>` still fails if kubo isn't connected to other libp2p nodes. Such connections aren't necessary to provide to an HTTP endpoint.

## Fix

Return the error `cannot provide, no connected peers`, only if no custom HTTP providers are configured AND kubo has no libp2p connections.

### CODE REVIEW

File: core/commands/routing.go [hunk 1]
```diff
@@ -170,12 +170,18 @@ var provideRefRoutingCmd = &cmds.Command{
 			return errors.New("invalid configuration: Provide.Enabled is set to 'false'")
 		}
 
-		if len(nd.PeerHost.Network().Conns()) == 0 && !httpProviderConfigured(cfg) {
```
Comment (guillaumemichel) [inline core/commands/routing.go]: The benefit of evaluating `httpProviderConfigured(cfg)` in the `if` is that it is evaluation only if the node has 0 connections. Otherwise, it adds some (small) overhead of reading the config for every call.

Only users with `custom` routing should pay the price of this check.

Comment (lidel) [reply core/commands/routing.go]: My bad, it was leftover from some tests i did, I've cleaned up in https://github.com/ipfs/kubo/pull/10974/commits/6fdf9299e159bd3254a11bc0f046c6c433f51d7e
Once CI is green I'll merge and start RC1 release dance

File: core/node/provider.go [hunk 2]
```diff
@@ -353,6 +353,12 @@ func SweepingProviderOpt(cfg *config.Config) fx.Option {
 			}
 		}
 		if impl == nil {
+			// No DHT available, check if HTTP provider is configured
+			cfg, err := in.Repo.Config()
+			if err == nil && cfg.HasHTTPProviderConfigured() {
+				// HTTP provider is configured, return NoopProvider to allow HTTP-based providing
+				return &NoopProvider{}, keyStore, nil
+			}
```
Comment (lidel) [inline core/node/provider.go:361]: Ok, tests failed because  SweepingProvider failed to initialize when there's no DHT available, even when HTTP routers were configured for providing. 

I've applied more surgical fix for now, will evaluate https://github.com/ipfs/kubo/pull/10975 later.

**Review by lidel — APPROVED** [review]
Did some refactoring, hopefully not breaking anything.
We will ask Plebbit to test once 0.38.0-rc1 is tagged so low risk to merge.
